stages:
  - test
  - compile

go-compile:test:
  image: golang:1.7.4
  stage: test
  before_script:
    - mkdir -p $GOPATH/src/github.com/mittwald
    - ln -nfs $PWD $GOPATH/src/github.com/mittwald/spacectl
    - cd $GOPATH/src/github.com/mittwald/spacectl
  script:
    - go build

go-compile:linux:
  image: golang:1.7.4
  stage: compile
  before_script:
    - mkdir -p $GOPATH/src/github.com/mittwald
    - ln -nfs $PWD $GOPATH/src/github.com/mittwald/spacectl
    - cd $GOPATH/src/github.com/mittwald/spacectl
  script:
    - CGO_ENABLED=0 GOOS=linux go build -o command-watcher-linux-amd64-${CI_BUILD_TAG} -ldflags "-s" -a -installsuffix cgo
  artifacts:
    paths:
      - ./command-watcher-linux-amd64-${CI_BUILD_TAG}
  only:
    - tags

go-compile:darwin:
  image: golang:1.7.4
  stage: compile
  before_script:
    - mkdir -p $GOPATH/src/github.com/mittwald
    - ln -nfs $PWD $GOPATH/src/github.com/mittwald/spacectl
    - cd $GOPATH/src/github.com/mittwald/spacectl
  script:
    - CGO_ENABLED=0 GOOS=darwin go build -o command-watcher-darwin-amd64-${CI_BUILD_TAG} -ldflags "-s" -a -installsuffix cgo
  artifacts:
    paths:
      - ./command-watcher-darwin-amd64-${CI_BUILD_TAG}
  only:
    - tags
